<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>MyTeam2</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>MyTeam2</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.myteam2</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Images\siteLogos\aek365.png" />
	  <None Remove="Resources\Images\siteLogos\aelole.png" />
	  <None Remove="Resources\Images\siteLogos\allaboutaris.png" />
	  <None Remove="Resources\Images\siteLogos\arisfc.png" />
	  <None Remove="Resources\Images\siteLogos\asports.png" />
	  <None Remove="Resources\Images\siteLogos\atromitosfc.png" />
	  <None Remove="Resources\Images\siteLogos\contra.png" />
	  <None Remove="Resources\Images\siteLogos\gavros.png" />
	  <None Remove="Resources\Images\siteLogos\gazzetta.png" />
	  <None Remove="Resources\Images\siteLogos\gentikoule.png" />
	  <None Remove="Resources\Images\siteLogos\inpaok.png" />
	  <None Remove="Resources\Images\siteLogos\kingsport.png" />
	  <None Remove="Resources\Images\siteLogos\lamia1964.png" />
	  <None Remove="Resources\Images\siteLogos\lamiara.png" />
	  <None Remove="Resources\Images\siteLogos\lamiaragate3.png" />
	  <None Remove="Resources\Images\siteLogos\leoforos.png" />
	  <None Remove="Resources\Images\siteLogos\metrosport.png" />
	  <None Remove="Resources\Images\siteLogos\newspao.png" />
	  <None Remove="Resources\Images\siteLogos\novasports.png" />
	  <None Remove="Resources\Images\siteLogos\olympiacosfc.png" />
	  <None Remove="Resources\Images\siteLogos\onsports.png" />
	  <None Remove="Resources\Images\siteLogos\panioniaIdea.png" />
	  <None Remove="Resources\Images\siteLogos\panioniosfc.png" />
	  <None Remove="Resources\Images\siteLogos\paok24.png" />
	  <None Remove="Resources\Images\siteLogos\paokfc.png" />
	  <None Remove="Resources\Images\siteLogos\planetaris.png" />
	  <None Remove="Resources\Images\siteLogos\prasinanea.png" />
	  <None Remove="Resources\Images\siteLogos\pressaris.png" />
	  <None Remove="Resources\Images\siteLogos\sdna.png" />
	  <None Remove="Resources\Images\siteLogos\sport24.png" />
	  <None Remove="Resources\Images\siteLogos\sportdog.png" />
	  <None Remove="Resources\Images\siteLogos\sportfm.png" />
	  <None Remove="Resources\Images\siteLogos\sportime.png" />
	  <None Remove="Resources\Images\siteLogos\sportlarissa.png" />
	  <None Remove="Resources\Images\siteLogos\sportsaddict.png" />
	  <None Remove="Resources\Images\siteLogos\thessports.png" />
	  <None Remove="Resources\Images\siteLogos\to10.png" />
	  <None Remove="Resources\Images\siteLogos\xanthisport.png" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Include="Resources\Images\siteLogos\aek365.png" />
	  <MauiImage Include="Resources\Images\siteLogos\aelole.png" />
	  <MauiImage Include="Resources\Images\siteLogos\allaboutaris.png" />
	  <MauiImage Include="Resources\Images\siteLogos\arisfc.png" />
	  <MauiImage Include="Resources\Images\siteLogos\asports.png" />
	  <MauiImage Include="Resources\Images\siteLogos\atromitosfc.png" />
	  <MauiImage Include="Resources\Images\siteLogos\contra.png" />
	  <MauiImage Include="Resources\Images\siteLogos\gavros.png" />
	  <MauiImage Include="Resources\Images\siteLogos\gazzetta.png" />
	  <MauiImage Include="Resources\Images\siteLogos\gentikoule.png" />
	  <MauiImage Include="Resources\Images\siteLogos\inpaok.png" />
	  <MauiImage Include="Resources\Images\siteLogos\kingsport.png" />
	  <MauiImage Include="Resources\Images\siteLogos\lamia1964.png" />
	  <MauiImage Include="Resources\Images\siteLogos\lamiara.png" />
	  <MauiImage Include="Resources\Images\siteLogos\lamiaragate3.png" />
	  <MauiImage Include="Resources\Images\siteLogos\leoforos.png" />
	  <MauiImage Include="Resources\Images\siteLogos\metrosport.png" />
	  <MauiImage Include="Resources\Images\siteLogos\newspao.png" />
	  <MauiImage Include="Resources\Images\siteLogos\novasports.png" />
	  <MauiImage Include="Resources\Images\siteLogos\olympiacosfc.png" />
	  <MauiImage Include="Resources\Images\siteLogos\onsports.png" />
	  <MauiImage Include="Resources\Images\siteLogos\panioniaidea.png" />
	  <MauiImage Include="Resources\Images\siteLogos\panioniosfc.png" />
	  <MauiImage Include="Resources\Images\siteLogos\paok24.png" />
	  <MauiImage Include="Resources\Images\siteLogos\paokfc.png" />
	  <MauiImage Include="Resources\Images\siteLogos\planetaris.png" />
	  <MauiImage Include="Resources\Images\siteLogos\prasinanea.png" />
	  <MauiImage Include="Resources\Images\siteLogos\pressaris.png" />
	  <MauiImage Include="Resources\Images\siteLogos\sdna.png" />
	  <MauiImage Include="Resources\Images\siteLogos\sport24.png" />
	  <MauiImage Include="Resources\Images\siteLogos\sportdog.png" />
	  <MauiImage Include="Resources\Images\siteLogos\sportfm.png" />
	  <MauiImage Include="Resources\Images\siteLogos\sportime.png" />
	  <MauiImage Include="Resources\Images\siteLogos\sportlarissa.png" />
	  <MauiImage Include="Resources\Images\siteLogos\sportsaddict.png" />
	  <MauiImage Include="Resources\Images\siteLogos\thessports.png" />
	  <MauiImage Include="Resources\Images\siteLogos\to10.png" />
	  <MauiImage Include="Resources\Images\siteLogos\xanthisport.png" />
	  <MauiImage Include="Resources\Images\teamLogos\aek.png" />
	  <MauiImage Include="Resources\Images\teamLogos\ael.png" />
	  <MauiImage Include="Resources\Images\teamLogos\apsmyrnis.png" />
	  <MauiImage Include="Resources\Images\teamLogos\aris.png" />
	  <MauiImage Include="Resources\Images\teamLogos\asterastrip.png" />
	  <MauiImage Include="Resources\Images\teamLogos\atromitos.png" />
	  <MauiImage Include="Resources\Images\teamLogos\iraklis.png" />
	  <MauiImage Include="Resources\Images\teamLogos\levadeiakos.png" />
	  <MauiImage Include="Resources\Images\teamLogos\ofi.png" />
	  <MauiImage Include="Resources\Images\teamLogos\osfp.png" />
	  <MauiImage Include="Resources\Images\teamLogos\panaitwlikos.png" />
	  <MauiImage Include="Resources\Images\teamLogos\panathinaikos.png" />
	  <MauiImage Include="Resources\Images\teamLogos\panionios.png" />
	  <MauiImage Include="Resources\Images\teamLogos\paok.png" />
	  <MauiImage Include="Resources\Images\teamLogos\pasgiannina.png" />
	  <MauiImage Include="Resources\Images\teamLogos\xanthi.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
		<PackageReference Include="Syncfusion.Maui.DataGrid" Version="30.1.42" />
		<PackageReference Include="Syncfusion.Maui.PullToRefresh" Version="30.1.42" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Pages\Settings\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
